name: Generate Ascii

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4 

        - name: Install cowsay
          run: sudo apt-get install cowsay -y

        - name: list repo files
          run: ls -ltra 

        - name: Executing file script
          run: |
            chmod +x ascii-script.sh
            ./ascii-script.sh
        